name: mess_manager
description: Mess financial tracker — ObjectBox, PDF, JSON backup.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1

  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

  pdf: ^3.11.1
  printing: ^5.13.1

  file_picker: ^8.1.2
  share_plus: ^10.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  objectbox_generator: ^4.0.1
  build_runner: ^2.4.12

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0D0D14"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  remove_alpha_ios: true
  web:
    generate: false

flutter:
  uses-material-design: true
