// ============================================================
// MessManager — main.dart  (ObjectBox edition)
// Single-file starter. Split into directories after first run.
// ============================================================

import 'dart:convert';
import 'dart:io';

import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:objectbox/objectbox.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'objectbox.g.dart'; // generated by build_runner

// ============================================================
// SECTION 1 — OBJECTBOX MODELS
// ============================================================

@Entity()
class Member {
  @Id()
  int id = 0;

  late String name;
  late String initials;
  late String avatarColor;
  bool isActive = true;
  late String joinedMonthId;
  DateTime? createdAt;

  Member({
    this.id = 0,
    this.name = '',
    this.initials = '',
    this.avatarColor = '7F77DD',
    this.isActive = true,
    this.joinedMonthId = '',
    this.createdAt,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'initials': initials,
    'avatarColor': avatarColor,
    'isActive': isActive,
    'joinedMonthId': joinedMonthId,
    'createdAt': createdAt?.toIso8601String(),
  };

  factory Member.fromJson(Map<String, dynamic> j) => Member(
    name: j['name'] ?? '',
    initials: j['initials'] ?? '',
    avatarColor: j['avatarColor'] ?? '7F77DD',
    isActive: j['isActive'] ?? true,
    joinedMonthId: j['joinedMonthId'] ?? '',
    createdAt:
    j['createdAt'] != null ? DateTime.parse(j['createdAt']) : null,
  );
}

@Entity()
class MealEntry {
  @Id()
  int id = 0;

  late int memberId;
  late int count;

  @Property(type: PropertyType.date)
  late DateTime date;

  late String monthId;

  MealEntry({
    this.id = 0,
    this.memberId = 0,
    this.count = 0,
    DateTime? date,
    this.monthId = '',
  }) : date = date ?? DateTime.now();

  Map<String, dynamic> toJson() => {
    'memberId': memberId,
    'count': count,
    'date': date.toIso8601String(),
    'monthId': monthId,
  };

  factory MealEntry.fromJson(Map<String, dynamic> j) => MealEntry(
    memberId: j['memberId'] ?? 0,
    count: j['count'] ?? 0,
    date: DateTime.parse(j['date']),
    monthId: j['monthId'] ?? '',
  );
}

@Entity()
class BazarEntry {
  @Id()
  int id = 0;

  late double amount;
  late String note;
  late String category;

  @Property(type: PropertyType.date)
  late DateTime date;

  late String monthId;

  BazarEntry({
    this.id = 0,
    this.amount = 0,
    this.note = '',
    this.category = 'General',
    DateTime? date,
    this.monthId = '',
  }) : date = date ?? DateTime.now();

  Map<String, dynamic> toJson() => {
    'amount': amount,
    'note': note,
    'category': category,
    'date': date.toIso8601String(),
    'monthId': monthId,
  };

  factory BazarEntry.fromJson(Map<String, dynamic> j) => BazarEntry(
    amount: (j['amount'] as num).toDouble(),
    note: j['note'] ?? '',
    category: j['category'] ?? 'General',
    date: DateTime.parse(j['date']),
    monthId: j['monthId'] ?? '',
  );
}

@Entity()
class OtherCost {
  @Id()
  int id = 0;

  late int memberId;
  late double amount;
  late String category;
  late String note;

  @Property(type: PropertyType.date)
  late DateTime date;

  late String monthId;

  OtherCost({
    this.id = 0,
    this.memberId = 0,
    this.amount = 0,
    this.category = 'Rent',
    this.note = '',
    DateTime? date,
    this.monthId = '',
  }) : date = date ?? DateTime.now();

  Map<String, dynamic> toJson() => {
    'memberId': memberId,
    'amount': amount,
    'category': category,
    'note': note,
    'date': date.toIso8601String(),
    'monthId': monthId,
  };

  factory OtherCost.fromJson(Map<String, dynamic> j) => OtherCost(
    memberId: j['memberId'] ?? 0,
    amount: (j['amount'] as num).toDouble(),
    category: j['category'] ?? 'Rent',
    note: j['note'] ?? '',
    date: DateTime.parse(j['date']),
    monthId: j['monthId'] ?? '',
  );
}

@Entity()
class Payment {
  @Id()
  int id = 0;

  late int memberId;
  late double amount;
  late String method;
  late String note;

  @Property(type: PropertyType.date)
  late DateTime date;

  late String monthId;

  Payment({
    this.id = 0,
    this.memberId = 0,
    this.amount = 0,
    this.method = 'Cash',
    this.note = '',
    DateTime? date,
    this.monthId = '',
  }) : date = date ?? DateTime.now();

  Map<String, dynamic> toJson() => {
    'memberId': memberId,
    'amount': amount,
    'method': method,
    'note': note,
    'date': date.toIso8601String(),
    'monthId': monthId,
  };

  factory Payment.fromJson(Map<String, dynamic> j) => Payment(
    memberId: j['memberId'] ?? 0,
    amount: (j['amount'] as num).toDouble(),
    method: j['method'] ?? 'Cash',
    note: j['note'] ?? '',
    date: DateTime.parse(j['date']),
    monthId: j['monthId'] ?? '',
  );
}

// ============================================================
// SECTION 2 — OBJECTBOX STORE SINGLETON
// ============================================================

late Store _store;

Future<void> _initStore() async {
  final dir = await getApplicationDocumentsDirectory();
  _store = await openStore(directory: '${dir.path}/mess_ob');
}

Box<Member>       get _memberBox    => _store.box<Member>();
Box<MealEntry>    get _mealBox      => _store.box<MealEntry>();
Box<BazarEntry>   get _bazarBox     => _store.box<BazarEntry>();
Box<OtherCost>    get _costBox      => _store.box<OtherCost>();
Box<Payment>      get _paymentBox   => _store.box<Payment>();

// ============================================================
// SECTION 3 — DATABASE SERVICE
// ============================================================

class DbService {
  // ── Members ──────────────────────────────────────────────
  List<Member> getActiveMembers() =>
      _memberBox.getAll().where((m) => m.isActive).toList();

  void saveMember(Member m) => _memberBox.put(m);

  void softDeleteMember(int id) {
    final m = _memberBox.get(id);
    if (m != null) {
      m.isActive = false;
      _memberBox.put(m);
    }
  }

  // ── Meals ─────────────────────────────────────────────────
  List<MealEntry> getMealsByMonth(String monthId) => _mealBox
      .getAll()
      .where((e) => e.monthId == monthId)
      .toList();

  void saveMeal(MealEntry e) => _mealBox.put(e);
  void deleteMeal(int id) => _mealBox.remove(id);

  // ── Bazar ─────────────────────────────────────────────────
  List<BazarEntry> getBazarByMonth(String monthId) => _bazarBox
      .getAll()
      .where((e) => e.monthId == monthId)
      .toList();

  void saveBazar(BazarEntry e) => _bazarBox.put(e);
  void deleteBazar(int id) => _bazarBox.remove(id);

  // ── Other Costs ───────────────────────────────────────────
  List<OtherCost> getCostsByMonth(String monthId) => _costBox
      .getAll()
      .where((e) => e.monthId == monthId)
      .toList();

  void saveCost(OtherCost e) => _costBox.put(e);
  void deleteCost(int id) => _costBox.remove(id);

  // ── Payments ──────────────────────────────────────────────
  List<Payment> getPaymentsByMonth(String monthId) => _paymentBox
      .getAll()
      .where((e) => e.monthId == monthId)
      .toList();

  void savePayment(Payment e) => _paymentBox.put(e);
  void deletePayment(int id) => _paymentBox.remove(id);

  // ── Month list ────────────────────────────────────────────
  List<String> getAllMonthIds() {
    final ids = _mealBox.getAll().map((e) => e.monthId).toSet().toList();
    ids.sort((a, b) => b.compareTo(a));
    return ids;
  }

  void clearMonth(String monthId) {
    final mealIds = _mealBox.getAll()
        .where((e) => e.monthId == monthId).map((e) => e.id).toList();
    final bazarIds = _bazarBox.getAll()
        .where((e) => e.monthId == monthId).map((e) => e.id).toList();
    final costIds = _costBox.getAll()
        .where((e) => e.monthId == monthId).map((e) => e.id).toList();
    final payIds = _paymentBox.getAll()
        .where((e) => e.monthId == monthId).map((e) => e.id).toList();

    _mealBox.removeMany(mealIds);
    _bazarBox.removeMany(bazarIds);
    _costBox.removeMany(costIds);
    _paymentBox.removeMany(payIds);
  }
}

final _db = DbService();

// ============================================================
// SECTION 4 — CALCULATION ENGINE
// ============================================================

class MemberSummary {
  final Member member;
  final int totalMeals;
  final double mealCost;
  final double otherCosts;
  final double totalCost;
  final double paid;
  final double due;

  MemberSummary({
    required this.member,
    required this.totalMeals,
    required this.mealCost,
    required this.otherCosts,
    required this.totalCost,
    required this.paid,
    required this.due,
  });

  bool get isSettled  => due.abs() < 0.01;
  bool get isOverpaid => due < -0.01;
  bool get hasDue     => due > 0.01;
}

class MonthSummary {
  final double totalBazar;
  final int totalMeals;
  final double mealRate;
  final double totalPaid;
  final double totalDue;
  final List<MemberSummary> members;

  MonthSummary({
    required this.totalBazar,
    required this.totalMeals,
    required this.mealRate,
    required this.totalPaid,
    required this.totalDue,
    required this.members,
  });
}

MonthSummary computeSummary(String monthId) {
  final members  = _db.getActiveMembers();
  final meals    = _db.getMealsByMonth(monthId);
  final bazar    = _db.getBazarByMonth(monthId);
  final costs    = _db.getCostsByMonth(monthId);
  final payments = _db.getPaymentsByMonth(monthId);

  final totalBazar  = bazar.fold(0.0, (s, b) => s + b.amount);
  final totalMeals  = meals.fold(0,   (s, m) => s + m.count);
  final mealRate    = totalMeals > 0 ? totalBazar / totalMeals : 0.0;

  final summaries = members.map((member) {
    final mCount = meals
        .where((m) => m.memberId == member.id)
        .fold(0, (s, m) => s + m.count);
    final mCost  = mCount * mealRate;
    final oCost  = costs
        .where((c) => c.memberId == member.id)
        .fold(0.0, (s, c) => s + c.amount);
    final paidAmt = payments
        .where((p) => p.memberId == member.id)
        .fold(0.0, (s, p) => s + p.amount);

    return MemberSummary(
      member: member,
      totalMeals: mCount,
      mealCost: mCost,
      otherCosts: oCost,
      totalCost: mCost + oCost,
      paid: paidAmt,
      due: mCost + oCost - paidAmt,
    );
  }).toList();

  return MonthSummary(
    totalBazar: totalBazar,
    totalMeals: totalMeals,
    mealRate: mealRate,
    totalPaid: payments.fold(0.0, (s, p) => s + p.amount),
    totalDue: summaries.where((s) => s.hasDue).fold(0.0, (s, m) => s + m.due),
    members: summaries,
  );
}

// ============================================================
// SECTION 5 — BACKUP MODEL
// ============================================================

class MessBackup {
  final String version;
  final String exportedAt;
  final String monthId;
  final List<Map<String, dynamic>> members;
  final List<Map<String, dynamic>> mealEntries;
  final List<Map<String, dynamic>> bazarEntries;
  final List<Map<String, dynamic>> otherCosts;
  final List<Map<String, dynamic>> payments;

  MessBackup({
    required this.version,
    required this.exportedAt,
    required this.monthId,
    required this.members,
    required this.mealEntries,
    required this.bazarEntries,
    required this.otherCosts,
    required this.payments,
  });

  Map<String, dynamic> toJson() => {
    'version':      version,
    'exportedAt':   exportedAt,
    'monthId':      monthId,
    'members':      members,
    'mealEntries':  mealEntries,
    'bazarEntries': bazarEntries,
    'otherCosts':   otherCosts,
    'payments':     payments,
  };

  factory MessBackup.fromJson(Map<String, dynamic> j) => MessBackup(
    version:      j['version'] ?? '1.0',
    exportedAt:   j['exportedAt'] ?? '',
    monthId:      j['monthId'] ?? '',
    members:      List<Map<String, dynamic>>.from(j['members']      ?? []),
    mealEntries:  List<Map<String, dynamic>>.from(j['mealEntries']  ?? []),
    bazarEntries: List<Map<String, dynamic>>.from(j['bazarEntries'] ?? []),
    otherCosts:   List<Map<String, dynamic>>.from(j['otherCosts']   ?? []),
    payments:     List<Map<String, dynamic>>.from(j['payments']     ?? []),
  );
}

// ============================================================
// SECTION 6 — EXPORT SERVICE
// ============================================================

class ExportService {
  Future<void> shareJson(String monthId) async {
    final summary  = computeSummary(monthId);
    final members  = _db.getActiveMembers();
    final meals    = _db.getMealsByMonth(monthId);
    final bazar    = _db.getBazarByMonth(monthId);
    final costs    = _db.getCostsByMonth(monthId);
    final payments = _db.getPaymentsByMonth(monthId);

    final backup = MessBackup(
      version:      '1.0',
      exportedAt:   DateTime.now().toIso8601String(),
      monthId:      monthId,
      members:      members.map((m) => m.toJson()).toList(),
      mealEntries:  meals.map((m) => m.toJson()).toList(),
      bazarEntries: bazar.map((b) => b.toJson()).toList(),
      otherCosts:   costs.map((c) => c.toJson()).toList(),
      payments:     payments.map((p) => p.toJson()).toList(),
    );

    final dir  = await getApplicationDocumentsDirectory();
    final file = File('${dir.path}/mess_backup_$monthId.json');
    await file.writeAsString(
        const JsonEncoder.withIndent('  ').convert(backup.toJson()));

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/json')],
      subject: 'MessManager backup — $monthId',
    );
  }

  Future<void> sharePdf(String monthId) async {
    final summary = computeSummary(monthId);

    final pdf = pw.Document();
    pdf.addPage(pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(36),
      build: (ctx) => [
        pw.Text('Mess Report — ${_formatMonthId(monthId)}',
            style: pw.TextStyle(
                fontSize: 22, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 6),
        pw.Text(
          'Meal rate: ৳${summary.mealRate.toStringAsFixed(2)}  |  '
              'Total meals: ${summary.totalMeals}  |  '
              'Bazar: ৳${summary.totalBazar.toStringAsFixed(0)}',
          style: const pw.TextStyle(
              fontSize: 11, color: PdfColors.grey700),
        ),
        pw.Divider(height: 24),
        ...summary.members.map((ms) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(ms.member.name,
                style: pw.TextStyle(
                    fontSize: 15,
                    fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 4),
            _pdfRow(
                'Meals (${ms.totalMeals} × ৳${summary.mealRate.toStringAsFixed(2)})',
                '৳${ms.mealCost.toStringAsFixed(0)}'),
            _pdfRow('Other costs',
                '৳${ms.otherCosts.toStringAsFixed(0)}'),
            _pdfRow('Total cost',
                '৳${ms.totalCost.toStringAsFixed(0)}',
                bold: true),
            _pdfRow('Paid', '৳${ms.paid.toStringAsFixed(0)}'),
            _pdfRow(
              ms.hasDue
                  ? 'Due'
                  : ms.isOverpaid
                  ? 'Advance'
                  : 'Settled',
              '৳${ms.due.abs().toStringAsFixed(0)}',
              bold: true,
              color: ms.hasDue
                  ? PdfColors.red700
                  : ms.isOverpaid
                  ? PdfColors.blue700
                  : PdfColors.green700,
            ),
            pw.Divider(height: 20),
          ],
        )),
      ],
    ));

    await Printing.sharePdf(
        bytes: await pdf.save(),
        filename: 'mess_report_$monthId.pdf');
  }

  pw.Widget _pdfRow(String label, String value,
      {bool bold = false, PdfColor? color}) {
    final style = pw.TextStyle(
        fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        color: color);
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 2),
      child: pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(label, style: style),
            pw.Text(value, style: style),
          ]),
    );
  }
}

// ============================================================
// SECTION 7 — IMPORT SERVICE
// ============================================================

class ImportResult {
  final bool success;
  final String message;
  final MessBackup? backup;
  ImportResult(
      {required this.success, required this.message, this.backup});
}

class ImportService {
  Future<ImportResult> pickFile() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['json'],
      dialogTitle: 'Select MessManager backup (.json)',
    );

    if (result == null || result.files.isEmpty) {
      return ImportResult(success: false, message: 'No file selected.');
    }

    final path = result.files.single.path;
    if (path == null) {
      return ImportResult(
          success: false, message: 'Cannot read file path.');
    }

    String raw;
    try {
      raw = await File(path).readAsString();
    } catch (e) {
      return ImportResult(
          success: false, message: 'Cannot read file: $e');
    }

    Map<String, dynamic> json;
    try {
      json = jsonDecode(raw);
    } catch (_) {
      return ImportResult(
          success: false,
          message: 'Invalid JSON. Is this a MessManager backup?');
    }

    if (!json.containsKey('monthId') || !json.containsKey('version')) {
      return ImportResult(
          success: false,
          message: 'Not a valid MessManager backup file.');
    }

    try {
      final backup = MessBackup.fromJson(json);
      return ImportResult(
          success: true,
          message: 'Ready to import ${backup.monthId}',
          backup: backup);
    } catch (e) {
      return ImportResult(
          success: false, message: 'Parse error: $e');
    }
  }

  void commitImport(MessBackup backup) {
    _db.clearMonth(backup.monthId);
    for (final m in backup.members) {
      _memberBox.put(Member.fromJson(m));
    }
    for (final m in backup.mealEntries) {
      _mealBox.put(MealEntry.fromJson(m));
    }
    for (final b in backup.bazarEntries) {
      _bazarBox.put(BazarEntry.fromJson(b));
    }
    for (final c in backup.otherCosts) {
      _costBox.put(OtherCost.fromJson(c));
    }
    for (final p in backup.payments) {
      _paymentBox.put(Payment.fromJson(p));
    }
  }
}

final _exportSvc = ExportService();
final _importSvc = ImportService();

// ============================================================
// SECTION 8 — HELPERS
// ============================================================

String _currentMonthId() {
  final n = DateTime.now();
  return '${n.year}-${n.month.toString().padLeft(2, '0')}';
}

String _formatMonthId(String id) {
  final parts = id.split('-');
  if (parts.length != 2) return id;
  const months = [
    '', 'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  final m = int.tryParse(parts[1]) ?? 0;
  return '${months[m]} ${parts[0]}';
}

// ============================================================
// SECTION 9 — APP ENTRY & THEME
// ============================================================

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await _initStore();
  runApp(const MessManagerApp());
}

class MessManagerApp extends StatefulWidget {
  const MessManagerApp({super.key});

  @override
  State<MessManagerApp> createState() => _MessManagerAppState();
}

class _MessManagerAppState extends State<MessManagerApp> {
  bool _isDark = false;

  @override
  void initState() {
    super.initState();
    _loadTheme();
  }

  Future<void> _loadTheme() async {
    final prefs = await SharedPreferences.getInstance();
    if (mounted) setState(() => _isDark = prefs.getBool('isDark') ?? false);
  }

  Future<void> _toggleTheme(bool val) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool('isDark', val);
    if (mounted) setState(() => _isDark = val);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'MessManager',
      debugShowCheckedModeBanner: false,
      themeMode: _isDark ? ThemeMode.dark : ThemeMode.light,
      theme: _buildTheme(Brightness.light),
      darkTheme: _buildTheme(Brightness.dark),
      home: MainShell(
          isDark: _isDark, onThemeToggle: _toggleTheme),
    );
  }

  ThemeData _buildTheme(Brightness brightness) {
    const primary = Color(0xFF1a1a2e);
    final dark = brightness == Brightness.dark;
    return ThemeData(
      useMaterial3: true,
      brightness: brightness,
      colorScheme:
      ColorScheme.fromSeed(seedColor: primary, brightness: brightness),
      scaffoldBackgroundColor:
      dark ? const Color(0xFF121212) : const Color(0xFFF5F5F5),
      cardTheme: CardThemeData(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(14),
          side: BorderSide(
              color: dark
                  ? Colors.white.withOpacity(0.08)
                  : Colors.black.withOpacity(0.08)),
        ),
        color: dark ? const Color(0xFF1E1E1E) : Colors.white,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: primary,
        foregroundColor: Colors.white,
        elevation: 0,
        centerTitle: false,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: dark
            ? Colors.white.withOpacity(0.06)
            : Colors.black.withOpacity(0.04),
        border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(10),
            borderSide: BorderSide.none),
        contentPadding:
        const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      ),
    );
  }
}

// ============================================================
// SECTION 10 — MAIN SHELL
// ============================================================

class MainShell extends StatefulWidget {
  final bool isDark;
  final ValueChanged<bool> onThemeToggle;
  const MainShell(
      {super.key, required this.isDark, required this.onThemeToggle});

  @override
  State<MainShell> createState() => _MainShellState();
}

class _MainShellState extends State<MainShell> {
  int _index = 0;
  final String _monthId = _currentMonthId();

  @override
  Widget build(BuildContext context) {
    final screens = [
      HomeScreen(monthId: _monthId),
      MealScreen(monthId: _monthId),
      BazarScreen(monthId: _monthId),
      OtherCostScreen(monthId: _monthId),
      PaymentScreen(monthId: _monthId),
      HistoryScreen(currentMonthId: _monthId),
      SettingsScreen(
          isDark: widget.isDark,
          onThemeToggle: widget.onThemeToggle),
    ];

    return Scaffold(
      body: IndexedStack(index: _index, children: screens),
      bottomNavigationBar: NavigationBar(
        selectedIndex: _index,
        onDestinationSelected: (i) => setState(() => _index = i),
        destinations: const [
          NavigationDestination(
              icon: Icon(Icons.dashboard_outlined),
              selectedIcon: Icon(Icons.dashboard_rounded),
              label: 'Home'),
          NavigationDestination(
              icon: Icon(Icons.restaurant_outlined),
              selectedIcon: Icon(Icons.restaurant_rounded),
              label: 'Meals'),
          NavigationDestination(
              icon: Icon(Icons.shopping_basket_outlined),
              selectedIcon: Icon(Icons.shopping_basket_rounded),
              label: 'Bazar'),
          NavigationDestination(
              icon: Icon(Icons.receipt_long_outlined),
              selectedIcon: Icon(Icons.receipt_long_rounded),
              label: 'Costs'),
          NavigationDestination(
              icon: Icon(Icons.payments_outlined),
              selectedIcon: Icon(Icons.payments_rounded),
              label: 'Pay'),
          NavigationDestination(
              icon: Icon(Icons.folder_outlined),
              selectedIcon: Icon(Icons.folder_rounded),
              label: 'History'),
          NavigationDestination(
              icon: Icon(Icons.settings_outlined),
              selectedIcon: Icon(Icons.settings_rounded),
              label: 'Settings'),
        ],
      ),
    );
  }
}

// ============================================================
// SECTION 11 — HOME SCREEN
// ============================================================

class HomeScreen extends StatefulWidget {
  final String monthId;
  const HomeScreen({super.key, required this.monthId});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  MonthSummary? _summary;
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _load();
  }

  void _load() {
    setState(() => _loading = true);
    final s = computeSummary(widget.monthId);
    setState(() {
      _summary = s;
      _loading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Text('Dashboard',
                  style: TextStyle(fontSize: 18)),
              Text(_formatMonthId(widget.monthId),
                  style: const TextStyle(
                      fontSize: 12, color: Colors.white70)),
            ]),
        actions: [
          IconButton(
              icon: const Icon(Icons.refresh_rounded),
              onPressed: _load),
        ],
      ),
      body: _loading
          ? const Center(child: CircularProgressIndicator())
          : RefreshIndicator(
        onRefresh: () async => _load(),
        child: ListView(
          padding: const EdgeInsets.all(14),
          children: [
            if (_summary != null) ...[
              _buildSummaryCards(_summary!),
              const SizedBox(height: 16),
              Row(children: [
                Text('Members',
                    style: Theme.of(context)
                        .textTheme
                        .titleSmall
                        ?.copyWith(color: Colors.grey)),
                const Spacer(),
                Text(
                    '${_summary!.members.length} active',
                    style:
                    Theme.of(context).textTheme.bodySmall),
              ]),
              const SizedBox(height: 8),
              ..._summary!.members.map(_buildMemberCard),
              if (_summary!.members.isEmpty)
                const Card(
                  child: Padding(
                    padding: EdgeInsets.all(20),
                    child: Column(children: [
                      Icon(Icons.people_outline,
                          size: 40, color: Colors.grey),
                      SizedBox(height: 8),
                      Text('No members yet.',
                          style:
                          TextStyle(color: Colors.grey)),
                      Text(
                          'Go to Settings → Add member first.',
                          style:
                          TextStyle(color: Colors.grey)),
                    ]),
                  ),
                ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildSummaryCards(MonthSummary s) {
    return Column(children: [
      Row(children: [
        Expanded(
            child: _metricCard('Meal rate',
                '৳${s.mealRate.toStringAsFixed(2)}', 'per meal')),
        const SizedBox(width: 8),
        Expanded(
            child: _metricCard(
                'Total meals', '${s.totalMeals}', 'this month')),
      ]),
      const SizedBox(height: 8),
      Row(children: [
        Expanded(
            child: _metricCard('Bazar cost',
                '৳${s.totalBazar.toStringAsFixed(0)}',
                widget.monthId)),
        const SizedBox(width: 8),
        Expanded(
            child: _metricCard('Total paid',
                '৳${s.totalPaid.toStringAsFixed(0)}', 'collected',
                color: Colors.green)),
      ]),
      const SizedBox(height: 8),
      _metricCard(
          'Outstanding',
          '৳${s.totalDue.toStringAsFixed(0)}',
          '${s.members.where((m) => m.hasDue).length} members owe',
          color: s.totalDue > 0 ? Colors.red : Colors.green,
          full: true),
    ]);
  }

  Widget _metricCard(String label, String value, String sub,
      {Color? color, bool full = false}) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(14),
        child:
        Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(label,
              style: const TextStyle(fontSize: 11, color: Colors.grey)),
          const SizedBox(height: 4),
          Text(value,
              style: TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.w600,
                  color: color)),
          Text(sub,
              style:
              const TextStyle(fontSize: 11, color: Colors.grey)),
        ]),
      ),
    );
  }

  Widget _buildMemberCard(MemberSummary ms) {
    final color = ms.hasDue
        ? Colors.red
        : ms.isOverpaid
        ? Colors.blue
        : Colors.green;
    final label = ms.hasDue
        ? '৳${ms.due.toStringAsFixed(0)} due'
        : ms.isOverpaid
        ? '+৳${ms.due.abs().toStringAsFixed(0)}'
        : 'Settled';

    return Card(
      margin: const EdgeInsets.only(bottom: 8),
      child: ListTile(
        leading: CircleAvatar(
          backgroundColor: color.withOpacity(0.15),
          child: Text(ms.member.initials,
              style: TextStyle(
                  color: color, fontWeight: FontWeight.bold)),
        ),
        title: Text(ms.member.name,
            style: const TextStyle(fontWeight: FontWeight.w500)),
        subtitle: Text('${ms.totalMeals} meals'),
        trailing: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.end,
          children: [
            Text(label,
                style: TextStyle(
                    color: color, fontWeight: FontWeight.w600)),
            Container(
              margin: const EdgeInsets.only(top: 4),
              padding:
              const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
              decoration: BoxDecoration(
                color: color.withOpacity(0.1),
                borderRadius: BorderRadius.circular(99),
              ),
              child: Text(
                ms.hasDue
                    ? 'due'
                    : ms.isOverpaid
                    ? 'overpaid'
                    : 'paid',
                style: TextStyle(fontSize: 10, color: color),
              ),
            ),
          ],
        ),
        onTap: () => _showMemberDetail(ms),
      ),
    );
  }

  void _showMemberDetail(MemberSummary ms) {
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      shape: const RoundedRectangleBorder(
          borderRadius:
          BorderRadius.vertical(top: Radius.circular(20))),
      builder: (_) => Padding(
        padding: const EdgeInsets.all(20),
        child: Column(mainAxisSize: MainAxisSize.min, children: [
          Container(
              width: 36,
              height: 4,
              decoration: BoxDecoration(
                  color: Colors.grey.shade300,
                  borderRadius: BorderRadius.circular(2))),
          const SizedBox(height: 16),
          Text(ms.member.name,
              style: const TextStyle(
                  fontSize: 18, fontWeight: FontWeight.bold)),
          const SizedBox(height: 12),
          _detailRow('Meal cost (${ms.totalMeals} meals)',
              '৳${ms.mealCost.toStringAsFixed(0)}'),
          _detailRow('Other costs',
              '৳${ms.otherCosts.toStringAsFixed(0)}'),
          _detailRow('Total cost',
              '৳${ms.totalCost.toStringAsFixed(0)}',
              bold: true),
          _detailRow('Paid', '৳${ms.paid.toStringAsFixed(0)}'),
          const Divider(),
          _detailRow(
            ms.hasDue
                ? 'Due'
                : ms.isOverpaid
                ? 'Advance'
                : 'Settled',
            '৳${ms.due.abs().toStringAsFixed(0)}',
            bold: true,
            color: ms.hasDue
                ? Colors.red
                : ms.isOverpaid
                ? Colors.blue
                : Colors.green,
          ),
          const SizedBox(height: 20),
        ]),
      ),
    );
  }

  Widget _detailRow(String label, String value,
      {bool bold = false, Color? color}) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 5),
      child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(label,
                style: TextStyle(
                    color: Colors.grey,
                    fontWeight:
                    bold ? FontWeight.bold : FontWeight.normal)),
            Text(value,
                style: TextStyle(
                    color: color,
                    fontWeight:
                    bold ? FontWeight.bold : FontWeight.normal)),
          ]),
    );
  }
}

// ============================================================
// SECTION 12 — MEAL SCREEN
// ============================================================

class MealScreen extends StatefulWidget {
  final String monthId;
  const MealScreen({super.key, required this.monthId});

  @override
  State<MealScreen> createState() => _MealScreenState();
}

class _MealScreenState extends State<MealScreen> {
  List<Member> _members = [];
  final Map<int, int> _counts = {};
  DateTime _date = DateTime.now();
  List<MealEntry> _recent = [];

  @override
  void initState() {
    super.initState();
    _load();
  }

  void _load() {
    final members = _db.getActiveMembers();
    final recent  = _db.getMealsByMonth(widget.monthId)
      ..sort((a, b) => b.date.compareTo(a.date));
    setState(() {
      _members = members;
      for (final m in members) _counts.putIfAbsent(m.id, () => 0);
      _recent = recent;
    });
  }

  void _save() {
    for (final member in _members) {
      final count = _counts[member.id] ?? 0;
      if (count > 0) {
        _db.saveMeal(MealEntry(
          memberId: member.id,
          count: count,
          date: _date,
          monthId: widget.monthId,
        ));
      }
    }
    _counts.updateAll((_, __) => 0);
    _load();
    ScaffoldMessenger.of(context)
        .showSnackBar(const SnackBar(content: Text('Meals saved!')));
  }

  @override
  Widget build(BuildContext context) {
    final total = _counts.values.fold(0, (s, v) => s + v);
    return Scaffold(
      appBar: AppBar(title: const Text('Meal entry')),
      body: ListView(padding: const EdgeInsets.all(14), children: [
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(children: [
              ListTile(
                contentPadding: EdgeInsets.zero,
                leading: const Icon(Icons.calendar_today_rounded),
                title: Text(
                    '${_date.day}/${_date.month}/${_date.year}'),
                subtitle: const Text('Tap to change date'),
                onTap: () async {
                  final d = await showDatePicker(
                    context: context,
                    initialDate: _date,
                    firstDate: DateTime(2024),
                    lastDate: DateTime.now(),
                  );
                  if (d != null) setState(() => _date = d);
                },
              ),
              const Divider(),
              ..._members.map((m) => Padding(
                padding: const EdgeInsets.symmetric(vertical: 6),
                child: Row(children: [
                  CircleAvatar(
                      radius: 16,
                      child: Text(m.initials,
                          style: const TextStyle(fontSize: 11))),
                  const SizedBox(width: 10),
                  Expanded(child: Text(m.name)),
                  _Stepper(
                    value: _counts[m.id] ?? 0,
                    onChanged: (v) =>
                        setState(() => _counts[m.id] = v),
                  ),
                ]),
              )),
              const Divider(),
              Row(
                  mainAxisAlignment:
                  MainAxisAlignment.spaceBetween,
                  children: [
                    const Text('Total today'),
                    Text('$total meals',
                        style: const TextStyle(
                            fontWeight: FontWeight.bold)),
                  ]),
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                    onPressed: total > 0 ? _save : null,
                    child: const Text('Save meals')),
              ),
            ]),
          ),
        ),
        const SizedBox(height: 16),
        Text('Recent entries',
            style: Theme.of(context)
                .textTheme
                .titleSmall
                ?.copyWith(color: Colors.grey)),
        const SizedBox(height: 8),
        ..._recent.take(15).map((e) {
          final member = _members.firstWhere(
                  (m) => m.id == e.memberId,
              orElse: () => Member(name: '?', initials: '?'));
          return Card(
            margin: const EdgeInsets.only(bottom: 6),
            child: ListTile(
              title: Text(member.name),
              subtitle: Text(
                  '${e.date.day}/${e.date.month}/${e.date.year}'),
              trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('${e.count} meals',
                        style: const TextStyle(
                            fontWeight: FontWeight.w600)),
                    IconButton(
                        icon: const Icon(Icons.delete_outline,
                            size: 18),
                        onPressed: () {
                          _db.deleteMeal(e.id);
                          _load();
                        }),
                  ]),
            ),
          );
        }),
      ]),
    );
  }
}

// ============================================================
// SECTION 13 — BAZAR SCREEN
// ============================================================

class BazarScreen extends StatefulWidget {
  final String monthId;
  const BazarScreen({super.key, required this.monthId});

  @override
  State<BazarScreen> createState() => _BazarScreenState();
}

class _BazarScreenState extends State<BazarScreen> {
  final _amountCtrl = TextEditingController();
  final _noteCtrl   = TextEditingController();
  String _category  = 'General';
  DateTime _date    = DateTime.now();
  List<BazarEntry> _entries = [];
  double _total = 0;

  static const _categories = [
    'General', 'Rice', 'Oil', 'Fish/Meat',
    'Vegetables', 'Spices', 'Gas', 'Other'
  ];

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _amountCtrl.dispose();
    _noteCtrl.dispose();
    super.dispose();
  }

  void _load() {
    final entries = _db.getBazarByMonth(widget.monthId)
      ..sort((a, b) => b.date.compareTo(a.date));
    setState(() {
      _entries = entries;
      _total = entries.fold(0.0, (s, e) => s + e.amount);
    });
  }

  void _save() {
    final amount = double.tryParse(_amountCtrl.text);
    if (amount == null || amount <= 0) return;
    _db.saveBazar(BazarEntry(
      amount: amount,
      note: _noteCtrl.text.trim(),
      category: _category,
      date: _date,
      monthId: widget.monthId,
    ));
    _amountCtrl.clear();
    _noteCtrl.clear();
    _load();
    ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Bazar entry added!')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Bazar / expenses')),
      body: ListView(padding: const EdgeInsets.all(14), children: [
        Row(children: [
          Expanded(
            child: Card(
              child: Padding(
                padding: const EdgeInsets.all(14),
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text('Total bazar',
                          style: TextStyle(
                              fontSize: 11, color: Colors.grey)),
                      Text('৳${_total.toStringAsFixed(0)}',
                          style: const TextStyle(
                              fontSize: 22,
                              fontWeight: FontWeight.bold)),
                    ]),
              ),
            ),
          ),
        ]),
        const SizedBox(height: 8),
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(children: [
              ListTile(
                contentPadding: EdgeInsets.zero,
                leading: const Icon(Icons.calendar_today_rounded),
                title: Text(
                    '${_date.day}/${_date.month}/${_date.year}'),
                onTap: () async {
                  final d = await showDatePicker(
                      context: context,
                      initialDate: _date,
                      firstDate: DateTime(2024),
                      lastDate: DateTime.now());
                  if (d != null) setState(() => _date = d);
                },
              ),
              TextField(
                controller: _amountCtrl,
                keyboardType: TextInputType.number,
                decoration:
                const InputDecoration(labelText: 'Amount (৳)'),
              ),
              const SizedBox(height: 10),
              DropdownButtonFormField<String>(
                value: _category,
                decoration:
                const InputDecoration(labelText: 'Category'),
                items: _categories
                    .map((c) =>
                    DropdownMenuItem(value: c, child: Text(c)))
                    .toList(),
                onChanged: (v) =>
                    setState(() => _category = v ?? 'General'),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _noteCtrl,
                decoration: const InputDecoration(
                    labelText: 'Note (optional)'),
              ),
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                    onPressed: _save,
                    child: const Text('Add bazar entry')),
              ),
            ]),
          ),
        ),
        const SizedBox(height: 16),
        Text('This month',
            style: Theme.of(context)
                .textTheme
                .titleSmall
                ?.copyWith(color: Colors.grey)),
        const SizedBox(height: 8),
        ..._entries.map((e) => Card(
          margin: const EdgeInsets.only(bottom: 6),
          child: ListTile(
            title: Text(e.category),
            subtitle: Text(
                '${e.date.day}/${e.date.month} · ${e.note}'),
            trailing: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text('৳${e.amount.toStringAsFixed(0)}',
                      style: const TextStyle(
                          fontWeight: FontWeight.w600)),
                  IconButton(
                      icon: const Icon(Icons.delete_outline,
                          size: 18),
                      onPressed: () {
                        _db.deleteBazar(e.id);
                        _load();
                      }),
                ]),
          ),
        )),
      ]),
    );
  }
}

// ============================================================
// SECTION 14 — OTHER COST SCREEN
// ============================================================

class OtherCostScreen extends StatefulWidget {
  final String monthId;
  const OtherCostScreen({super.key, required this.monthId});

  @override
  State<OtherCostScreen> createState() => _OtherCostScreenState();
}

class _OtherCostScreenState extends State<OtherCostScreen> {
  final _amountCtrl = TextEditingController();
  final _noteCtrl   = TextEditingController();
  List<Member> _members     = [];
  Member? _selectedMember;
  String _category          = 'Rent';
  List<OtherCost> _entries  = [];

  static const _categories = [
    'Rent', 'Gas', 'Wifi', 'Maid', 'Repair', 'Other'
  ];

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _amountCtrl.dispose();
    _noteCtrl.dispose();
    super.dispose();
  }

  void _load() {
    final members = _db.getActiveMembers();
    final entries = _db.getCostsByMonth(widget.monthId)
      ..sort((a, b) => b.date.compareTo(a.date));
    setState(() {
      _members = members;
      _selectedMember ??= members.isNotEmpty ? members.first : null;
      _entries = entries;
    });
  }

  void _save() {
    final member = _selectedMember;
    final amount = double.tryParse(_amountCtrl.text);
    if (member == null || amount == null || amount <= 0) return;
    _db.saveCost(OtherCost(
      memberId: member.id,
      amount: amount,
      category: _category,
      note: _noteCtrl.text.trim(),
      monthId: widget.monthId,
    ));
    _amountCtrl.clear();
    _noteCtrl.clear();
    _load();
    ScaffoldMessenger.of(context)
        .showSnackBar(const SnackBar(content: Text('Cost added!')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Other costs')),
      body: ListView(padding: const EdgeInsets.all(14), children: [
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(children: [
              if (_members.isNotEmpty)
                DropdownButtonFormField<Member>(
                  value: _selectedMember,
                  decoration: const InputDecoration(
                      labelText: 'Assign to member'),
                  items: _members
                      .map((m) => DropdownMenuItem(
                      value: m, child: Text(m.name)))
                      .toList(),
                  onChanged: (v) =>
                      setState(() => _selectedMember = v),
                ),
              const SizedBox(height: 10),
              DropdownButtonFormField<String>(
                value: _category,
                decoration:
                const InputDecoration(labelText: 'Category'),
                items: _categories
                    .map((c) =>
                    DropdownMenuItem(value: c, child: Text(c)))
                    .toList(),
                onChanged: (v) =>
                    setState(() => _category = v ?? 'Rent'),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _amountCtrl,
                keyboardType: TextInputType.number,
                decoration:
                const InputDecoration(labelText: 'Amount (৳)'),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _noteCtrl,
                decoration: const InputDecoration(
                    labelText: 'Note (optional)'),
              ),
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                    onPressed: _save,
                    child: const Text('Add cost')),
              ),
            ]),
          ),
        ),
        const SizedBox(height: 16),
        Text('This month',
            style: Theme.of(context)
                .textTheme
                .titleSmall
                ?.copyWith(color: Colors.grey)),
        const SizedBox(height: 8),
        ..._entries.map((e) {
          final member = _members.firstWhere(
                  (m) => m.id == e.memberId,
              orElse: () => Member(name: 'Unknown', initials: '?'));
          return Card(
            margin: const EdgeInsets.only(bottom: 6),
            child: ListTile(
              title: Text('${member.name} · ${e.category}'),
              subtitle: Text(
                  '${e.date.day}/${e.date.month} · ${e.note}'),
              trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('৳${e.amount.toStringAsFixed(0)}',
                        style: const TextStyle(
                            fontWeight: FontWeight.w600)),
                    IconButton(
                        icon: const Icon(Icons.delete_outline,
                            size: 18),
                        onPressed: () {
                          _db.deleteCost(e.id);
                          _load();
                        }),
                  ]),
            ),
          );
        }),
      ]),
    );
  }
}

// ============================================================
// SECTION 15 — PAYMENT SCREEN
// ============================================================

class PaymentScreen extends StatefulWidget {
  final String monthId;
  const PaymentScreen({super.key, required this.monthId});

  @override
  State<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends State<PaymentScreen> {
  final _amountCtrl = TextEditingController();
  final _noteCtrl   = TextEditingController();
  List<Member> _members    = [];
  Member? _selectedMember;
  String _method           = 'Cash';
  List<Payment> _entries   = [];

  static const _methods = [
    'Cash', 'bKash', 'Nagad', 'Bank', 'Other'
  ];

  @override
  void initState() {
    super.initState();
    _load();
  }

  @override
  void dispose() {
    _amountCtrl.dispose();
    _noteCtrl.dispose();
    super.dispose();
  }

  void _load() {
    final members = _db.getActiveMembers();
    final entries = _db.getPaymentsByMonth(widget.monthId)
      ..sort((a, b) => b.date.compareTo(a.date));
    setState(() {
      _members = members;
      _selectedMember ??= members.isNotEmpty ? members.first : null;
      _entries = entries;
    });
  }

  void _save() {
    final member = _selectedMember;
    final amount = double.tryParse(_amountCtrl.text);
    if (member == null || amount == null || amount <= 0) return;
    _db.savePayment(Payment(
      memberId: member.id,
      amount: amount,
      method: _method,
      note: _noteCtrl.text.trim(),
      monthId: widget.monthId,
    ));
    _amountCtrl.clear();
    _noteCtrl.clear();
    _load();
    ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Payment recorded!')));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Payments')),
      body: ListView(padding: const EdgeInsets.all(14), children: [
        Card(
          child: Padding(
            padding: const EdgeInsets.all(16),
            child: Column(children: [
              if (_members.isNotEmpty)
                DropdownButtonFormField<Member>(
                  value: _selectedMember,
                  decoration:
                  const InputDecoration(labelText: 'Member'),
                  items: _members
                      .map((m) => DropdownMenuItem(
                      value: m, child: Text(m.name)))
                      .toList(),
                  onChanged: (v) =>
                      setState(() => _selectedMember = v),
                ),
              const SizedBox(height: 10),
              TextField(
                controller: _amountCtrl,
                keyboardType: TextInputType.number,
                decoration:
                const InputDecoration(labelText: 'Amount (৳)'),
              ),
              const SizedBox(height: 10),
              DropdownButtonFormField<String>(
                value: _method,
                decoration: const InputDecoration(
                    labelText: 'Payment method'),
                items: _methods
                    .map((m) =>
                    DropdownMenuItem(value: m, child: Text(m)))
                    .toList(),
                onChanged: (v) =>
                    setState(() => _method = v ?? 'Cash'),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: _noteCtrl,
                decoration: const InputDecoration(
                    labelText: 'Note (optional)'),
              ),
              const SizedBox(height: 12),
              SizedBox(
                width: double.infinity,
                child: FilledButton(
                    onPressed: _save,
                    child: const Text('Record payment')),
              ),
            ]),
          ),
        ),
        const SizedBox(height: 16),
        Text('Payment log',
            style: Theme.of(context)
                .textTheme
                .titleSmall
                ?.copyWith(color: Colors.grey)),
        const SizedBox(height: 8),
        ..._entries.map((e) {
          final member = _members.firstWhere(
                  (m) => m.id == e.memberId,
              orElse: () => Member(name: 'Unknown', initials: '?'));
          return Card(
            margin: const EdgeInsets.only(bottom: 6),
            child: ListTile(
              leading: const Icon(Icons.check_circle_outline,
                  color: Colors.green),
              title: Text(member.name),
              subtitle: Text(
                  '${e.method} · ${e.date.day}/${e.date.month}/${e.date.year}'),
              trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Text('৳${e.amount.toStringAsFixed(0)}',
                        style: const TextStyle(
                            fontWeight: FontWeight.w600,
                            color: Colors.green)),
                    IconButton(
                        icon: const Icon(Icons.delete_outline,
                            size: 18),
                        onPressed: () {
                          _db.deletePayment(e.id);
                          _load();
                        }),
                  ]),
            ),
          );
        }),
      ]),
    );
  }
}

// ============================================================
// SECTION 16 — HISTORY SCREEN
// ============================================================

class HistoryScreen extends StatefulWidget {
  final String currentMonthId;
  const HistoryScreen({super.key, required this.currentMonthId});

  @override
  State<HistoryScreen> createState() => _HistoryScreenState();
}

class _HistoryScreenState extends State<HistoryScreen> {
  List<String> _monthIds = [];

  @override
  void initState() {
    super.initState();
    _load();
  }

  void _load() {
    setState(() => _monthIds = _db.getAllMonthIds());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Monthly history'),
        actions: [
          IconButton(
              icon: const Icon(Icons.refresh_rounded),
              onPressed: _load),
        ],
      ),
      body: _monthIds.isEmpty
          ? const Center(
          child: Padding(
            padding: EdgeInsets.all(32),
            child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Icon(Icons.folder_open, size: 48, color: Colors.grey),
                  SizedBox(height: 12),
                  Text('No history yet.',
                      style: TextStyle(color: Colors.grey)),
                  Text('Add meals to start building history.',
                      style: TextStyle(color: Colors.grey)),
                ]),
          ))
          : ListView.separated(
        padding: const EdgeInsets.all(14),
        itemCount: _monthIds.length,
        separatorBuilder: (_, __) => const SizedBox(height: 8),
        itemBuilder: (_, i) {
          final id = _monthIds[i];
          final isCurrent = id == widget.currentMonthId;
          return Card(
            child: ListTile(
              leading: Icon(Icons.folder_rounded,
                  color: isCurrent
                      ? Theme.of(context).colorScheme.primary
                      : Colors.grey),
              title: Text(_formatMonthId(id),
                  style: const TextStyle(
                      fontWeight: FontWeight.w500)),
              subtitle: Text(isCurrent ? 'Active' : 'Archived'),
              trailing: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    TextButton(
                      onPressed: () => _exportSvc.shareJson(id),
                      child: const Text('JSON'),
                    ),
                    TextButton(
                      onPressed: () => _exportSvc.sharePdf(id),
                      child: const Text('PDF'),
                    ),
                  ]),
            ),
          );
        },
      ),
    );
  }
}

// ============================================================
// SECTION 17 — SETTINGS SCREEN
// ============================================================

class SettingsScreen extends StatefulWidget {
  final bool isDark;
  final ValueChanged<bool> onThemeToggle;
  const SettingsScreen(
      {super.key, required this.isDark, required this.onThemeToggle});

  @override
  State<SettingsScreen> createState() => _SettingsScreenState();
}

class _SettingsScreenState extends State<SettingsScreen> {
  List<Member> _members = [];

  @override
  void initState() {
    super.initState();
    _loadMembers();
  }

  void _loadMembers() {
    setState(() => _members = _db.getActiveMembers());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Settings')),
      body: ListView(padding: const EdgeInsets.all(14), children: [

        // ── Members ──────────────────────────────────────────
        _sectionLabel('Members'),
        ..._members.map((m) => Card(
          margin: const EdgeInsets.only(bottom: 6),
          child: ListTile(
            leading: CircleAvatar(
                child: Text(m.initials,
                    style: const TextStyle(fontSize: 12))),
            title: Text(m.name),
            subtitle: Text('Joined ${_formatMonthId(m.joinedMonthId)}'),
            trailing: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  IconButton(
                      icon: const Icon(Icons.edit_outlined,
                          size: 18),
                      onPressed: () =>
                          _showMemberDialog(member: m)),
                  IconButton(
                      icon: const Icon(
                          Icons.person_remove_outlined,
                          size: 18,
                          color: Colors.red),
                      onPressed: () =>
                          _confirmSoftDelete(m)),
                ]),
          ),
        )),
        Card(
          margin: const EdgeInsets.only(bottom: 6),
          child: ListTile(
            leading: const Icon(Icons.person_add_outlined),
            title: const Text('Add member'),
            onTap: () => _showMemberDialog(),
          ),
        ),

        const SizedBox(height: 12),
        // ── Appearance ───────────────────────────────────────
        _sectionLabel('Appearance'),
        Card(
          child: SwitchListTile(
            secondary: const Icon(Icons.dark_mode_outlined),
            title: const Text('Dark mode'),
            value: widget.isDark,
            onChanged: widget.onThemeToggle,
          ),
        ),

        const SizedBox(height: 12),
        // ── Data & export ─────────────────────────────────────
        _sectionLabel('Data & export'),
        Card(
          child: Column(children: [
            ListTile(
              leading: const Icon(Icons.code_rounded),
              title: const Text('Export JSON backup'),
              subtitle: const Text('Current month — importable later'),
              onTap: () => _exportSvc.shareJson(_currentMonthId()),
            ),
            const Divider(height: 0, indent: 16),
            ListTile(
              leading:
              const Icon(Icons.picture_as_pdf_rounded),
              title: const Text('Export PDF report'),
              subtitle:
              const Text('Current month — formatted summary'),
              onTap: () => _exportSvc.sharePdf(_currentMonthId()),
            ),
            const Divider(height: 0, indent: 16),
            ListTile(
              leading: const Icon(Icons.upload_file_rounded),
              title: const Text('Import from backup'),
              subtitle: const Text('Pick a .json MessManager file'),
              onTap: _runImport,
            ),
          ]),
        ),

        const SizedBox(height: 24),
        Center(
          child: Text(
            'MessManager v1.0.0 · Local-first · ObjectBox',
            style: TextStyle(
                fontSize: 11,
                color: Colors.grey.withOpacity(0.6)),
          ),
        ),
        const SizedBox(height: 8),
      ]),
    );
  }

  Widget _sectionLabel(String label) => Padding(
    padding: const EdgeInsets.only(bottom: 8, top: 4),
    child: Text(label.toUpperCase(),
        style: const TextStyle(
            fontSize: 11,
            color: Colors.grey,
            letterSpacing: 0.8,
            fontWeight: FontWeight.w500)),
  );

  void _showMemberDialog({Member? member}) {
    final nameCtrl =
    TextEditingController(text: member?.name ?? '');
    final initCtrl =
    TextEditingController(text: member?.initials ?? '');

    showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: Text(member == null ? 'Add member' : 'Edit member'),
        content: Column(mainAxisSize: MainAxisSize.min, children: [
          TextField(
            controller: nameCtrl,
            decoration:
            const InputDecoration(labelText: 'Full name'),
            autofocus: true,
            textCapitalization: TextCapitalization.words,
          ),
          const SizedBox(height: 10),
          TextField(
            controller: initCtrl,
            decoration: const InputDecoration(
                labelText: 'Initials (e.g. IM)'),
            maxLength: 2,
            textCapitalization: TextCapitalization.characters,
          ),
        ]),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Cancel')),
          FilledButton(
              onPressed: () {
                final name = nameCtrl.text.trim();
                final init =
                initCtrl.text.trim().toUpperCase();
                if (name.isEmpty || init.isEmpty) return;
                final m = member ?? Member();
                m.name = name;
                m.initials = init;
                m.isActive = true;
                m.joinedMonthId = _currentMonthId();
                m.createdAt = DateTime.now();
                _db.saveMember(m);
                Navigator.pop(context);
                _loadMembers();
              },
              child: const Text('Save')),
        ],
      ),
    );
  }

  Future<void> _confirmSoftDelete(Member m) async {
    final ok = await showDialog<bool>(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Remove member?'),
        content: Text(
            '${m.name} will be hidden but all their data is preserved.'),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel')),
          TextButton(
              style: TextButton.styleFrom(
                  foregroundColor: Colors.red),
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Remove')),
        ],
      ),
    );
    if (ok == true) {
      _db.softDeleteMember(m.id);
      _loadMembers();
    }
  }

  Future<void> _runImport() async {
    final result = await _importSvc.pickFile();
    if (!mounted) return;

    if (!result.success) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
          content: Text(result.message),
          backgroundColor: Colors.red));
      return;
    }

    final ok = await showDialog<bool>(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Import backup?'),
        content: Text(
            'This replaces all data for '
                '${_formatMonthId(result.backup!.monthId)}.\n\n'
                'Other months are not affected.'),
        actions: [
          TextButton(
              onPressed: () => Navigator.pop(context, false),
              child: const Text('Cancel')),
          FilledButton(
              onPressed: () => Navigator.pop(context, true),
              child: const Text('Import')),
        ],
      ),
    );

    if (ok == true && result.backup != null) {
      _importSvc.commitImport(result.backup!);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
                content: Text('Import successful!'),
                backgroundColor: Colors.green));
        _loadMembers();
      }
    }
  }
}

// ============================================================
// SECTION 18 — SHARED WIDGET: STEPPER
// ============================================================

class _Stepper extends StatelessWidget {
  final int value;
  final ValueChanged<int> onChanged;
  const _Stepper({required this.value, required this.onChanged});

  @override
  Widget build(BuildContext context) {
    return Row(mainAxisSize: MainAxisSize.min, children: [
      IconButton(
        onPressed: value > 0 ? () => onChanged(value - 1) : null,
        icon: const Icon(Icons.remove_circle_outline),
        iconSize: 22,
      ),
      SizedBox(
        width: 28,
        child: Text('$value',
            textAlign: TextAlign.center,
            style: const TextStyle(
                fontSize: 16, fontWeight: FontWeight.bold)),
      ),
      IconButton(
        onPressed: () => onChanged(value + 1),
        icon: const Icon(Icons.add_circle_outline),
        iconSize: 22,
      ),
    ]);
  }
}