// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'main.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 740230323287479855),
      name: 'BazarEntry',
      lastPropertyId: const obx_int.IdUid(6, 4279218504094721591),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4612780976459851537),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6589230579631983682),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7356350569760268941),
            name: 'note',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2360629371915086866),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4776119724427859936),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4279218504094721591),
            name: 'monthId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 7927114863390373332),
      name: 'MealEntry',
      lastPropertyId: const obx_int.IdUid(5, 5422120667833500387),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3915013264651188286),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 429568086495976715),
            name: 'memberId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1607890485219976871),
            name: 'count',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5201958651177109282),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5422120667833500387),
            name: 'monthId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 7243923060690246910),
      name: 'Member',
      lastPropertyId: const obx_int.IdUid(7, 7177452149058422318),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7876131625999066116),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3246853045866015014),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2535553284834305609),
            name: 'initials',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3815924620290975885),
            name: 'avatarColor',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7344541102709676482),
            name: 'isActive',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 583086586540456855),
            name: 'joinedMonthId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 7177452149058422318),
            name: 'createdAt',
            type: 10,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 6812378176094233437),
      name: 'OtherCost',
      lastPropertyId: const obx_int.IdUid(7, 4272243977907168170),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4561705398659017155),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3159621226226788403),
            name: 'memberId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6884216723432152691),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9054306635361362919),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2873148344280119084),
            name: 'note',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7594165227018382808),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4272243977907168170),
            name: 'monthId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 7216062852827631512),
      name: 'Payment',
      lastPropertyId: const obx_int.IdUid(7, 3003307600033182728),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3331544807165476299),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6063196303353159577),
            name: 'memberId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 4428480936144859339),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7150651432773044233),
            name: 'method',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 6390143879499803441),
            name: 'note',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6038522804417990069),
            name: 'date',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3003307600033182728),
            name: 'monthId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(5, 7216062852827631512),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    BazarEntry: obx_int.EntityDefinition<BazarEntry>(
        model: _entities[0],
        toOneRelations: (BazarEntry object) => [],
        toManyRelations: (BazarEntry object) => {},
        getId: (BazarEntry object) => object.id,
        setId: (BazarEntry object, int id) {
          object.id = id;
        },
        objectToFB: (BazarEntry object, fb.Builder fbb) {
          final noteOffset = fbb.writeString(object.note);
          final categoryOffset = fbb.writeString(object.category);
          final monthIdOffset = fbb.writeString(object.monthId);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addFloat64(1, object.amount);
          fbb.addOffset(2, noteOffset);
          fbb.addOffset(3, categoryOffset);
          fbb.addInt64(4, object.date.millisecondsSinceEpoch);
          fbb.addOffset(5, monthIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final noteParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final monthIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = BazarEntry(
              id: idParam,
              amount: amountParam,
              note: noteParam,
              category: categoryParam,
              date: dateParam,
              monthId: monthIdParam);

          return object;
        }),
    MealEntry: obx_int.EntityDefinition<MealEntry>(
        model: _entities[1],
        toOneRelations: (MealEntry object) => [],
        toManyRelations: (MealEntry object) => {},
        getId: (MealEntry object) => object.id,
        setId: (MealEntry object, int id) {
          object.id = id;
        },
        objectToFB: (MealEntry object, fb.Builder fbb) {
          final monthIdOffset = fbb.writeString(object.monthId);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.memberId);
          fbb.addInt64(2, object.count);
          fbb.addInt64(3, object.date.millisecondsSinceEpoch);
          fbb.addOffset(4, monthIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final memberIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final countParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final monthIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = MealEntry(
              id: idParam,
              memberId: memberIdParam,
              count: countParam,
              date: dateParam,
              monthId: monthIdParam);

          return object;
        }),
    Member: obx_int.EntityDefinition<Member>(
        model: _entities[2],
        toOneRelations: (Member object) => [],
        toManyRelations: (Member object) => {},
        getId: (Member object) => object.id,
        setId: (Member object, int id) {
          object.id = id;
        },
        objectToFB: (Member object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final initialsOffset = fbb.writeString(object.initials);
          final avatarColorOffset = fbb.writeString(object.avatarColor);
          final joinedMonthIdOffset = fbb.writeString(object.joinedMonthId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, initialsOffset);
          fbb.addOffset(3, avatarColorOffset);
          fbb.addBool(4, object.isActive);
          fbb.addOffset(5, joinedMonthIdOffset);
          fbb.addInt64(6, object.createdAt?.millisecondsSinceEpoch);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final createdAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final initialsParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final avatarColorParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final isActiveParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final joinedMonthIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final createdAtParam = createdAtValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(createdAtValue);
          final object = Member(
              id: idParam,
              name: nameParam,
              initials: initialsParam,
              avatarColor: avatarColorParam,
              isActive: isActiveParam,
              joinedMonthId: joinedMonthIdParam,
              createdAt: createdAtParam);

          return object;
        }),
    OtherCost: obx_int.EntityDefinition<OtherCost>(
        model: _entities[3],
        toOneRelations: (OtherCost object) => [],
        toManyRelations: (OtherCost object) => {},
        getId: (OtherCost object) => object.id,
        setId: (OtherCost object, int id) {
          object.id = id;
        },
        objectToFB: (OtherCost object, fb.Builder fbb) {
          final categoryOffset = fbb.writeString(object.category);
          final noteOffset = fbb.writeString(object.note);
          final monthIdOffset = fbb.writeString(object.monthId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.memberId);
          fbb.addFloat64(2, object.amount);
          fbb.addOffset(3, categoryOffset);
          fbb.addOffset(4, noteOffset);
          fbb.addInt64(5, object.date.millisecondsSinceEpoch);
          fbb.addOffset(6, monthIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final memberIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final noteParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final monthIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = OtherCost(
              id: idParam,
              memberId: memberIdParam,
              amount: amountParam,
              category: categoryParam,
              note: noteParam,
              date: dateParam,
              monthId: monthIdParam);

          return object;
        }),
    Payment: obx_int.EntityDefinition<Payment>(
        model: _entities[4],
        toOneRelations: (Payment object) => [],
        toManyRelations: (Payment object) => {},
        getId: (Payment object) => object.id,
        setId: (Payment object, int id) {
          object.id = id;
        },
        objectToFB: (Payment object, fb.Builder fbb) {
          final methodOffset = fbb.writeString(object.method);
          final noteOffset = fbb.writeString(object.note);
          final monthIdOffset = fbb.writeString(object.monthId);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.memberId);
          fbb.addFloat64(2, object.amount);
          fbb.addOffset(3, methodOffset);
          fbb.addOffset(4, noteOffset);
          fbb.addInt64(5, object.date.millisecondsSinceEpoch);
          fbb.addOffset(6, monthIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final memberIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final methodParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final noteParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));
          final monthIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final object = Payment(
              id: idParam,
              memberId: memberIdParam,
              amount: amountParam,
              method: methodParam,
              note: noteParam,
              date: dateParam,
              monthId: monthIdParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [BazarEntry] entity fields to define ObjectBox queries.
class BazarEntry_ {
  /// See [BazarEntry.id].
  static final id =
      obx.QueryIntegerProperty<BazarEntry>(_entities[0].properties[0]);

  /// See [BazarEntry.amount].
  static final amount =
      obx.QueryDoubleProperty<BazarEntry>(_entities[0].properties[1]);

  /// See [BazarEntry.note].
  static final note =
      obx.QueryStringProperty<BazarEntry>(_entities[0].properties[2]);

  /// See [BazarEntry.category].
  static final category =
      obx.QueryStringProperty<BazarEntry>(_entities[0].properties[3]);

  /// See [BazarEntry.date].
  static final date =
      obx.QueryDateProperty<BazarEntry>(_entities[0].properties[4]);

  /// See [BazarEntry.monthId].
  static final monthId =
      obx.QueryStringProperty<BazarEntry>(_entities[0].properties[5]);
}

/// [MealEntry] entity fields to define ObjectBox queries.
class MealEntry_ {
  /// See [MealEntry.id].
  static final id =
      obx.QueryIntegerProperty<MealEntry>(_entities[1].properties[0]);

  /// See [MealEntry.memberId].
  static final memberId =
      obx.QueryIntegerProperty<MealEntry>(_entities[1].properties[1]);

  /// See [MealEntry.count].
  static final count =
      obx.QueryIntegerProperty<MealEntry>(_entities[1].properties[2]);

  /// See [MealEntry.date].
  static final date =
      obx.QueryDateProperty<MealEntry>(_entities[1].properties[3]);

  /// See [MealEntry.monthId].
  static final monthId =
      obx.QueryStringProperty<MealEntry>(_entities[1].properties[4]);
}

/// [Member] entity fields to define ObjectBox queries.
class Member_ {
  /// See [Member.id].
  static final id =
      obx.QueryIntegerProperty<Member>(_entities[2].properties[0]);

  /// See [Member.name].
  static final name =
      obx.QueryStringProperty<Member>(_entities[2].properties[1]);

  /// See [Member.initials].
  static final initials =
      obx.QueryStringProperty<Member>(_entities[2].properties[2]);

  /// See [Member.avatarColor].
  static final avatarColor =
      obx.QueryStringProperty<Member>(_entities[2].properties[3]);

  /// See [Member.isActive].
  static final isActive =
      obx.QueryBooleanProperty<Member>(_entities[2].properties[4]);

  /// See [Member.joinedMonthId].
  static final joinedMonthId =
      obx.QueryStringProperty<Member>(_entities[2].properties[5]);

  /// See [Member.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Member>(_entities[2].properties[6]);
}

/// [OtherCost] entity fields to define ObjectBox queries.
class OtherCost_ {
  /// See [OtherCost.id].
  static final id =
      obx.QueryIntegerProperty<OtherCost>(_entities[3].properties[0]);

  /// See [OtherCost.memberId].
  static final memberId =
      obx.QueryIntegerProperty<OtherCost>(_entities[3].properties[1]);

  /// See [OtherCost.amount].
  static final amount =
      obx.QueryDoubleProperty<OtherCost>(_entities[3].properties[2]);

  /// See [OtherCost.category].
  static final category =
      obx.QueryStringProperty<OtherCost>(_entities[3].properties[3]);

  /// See [OtherCost.note].
  static final note =
      obx.QueryStringProperty<OtherCost>(_entities[3].properties[4]);

  /// See [OtherCost.date].
  static final date =
      obx.QueryDateProperty<OtherCost>(_entities[3].properties[5]);

  /// See [OtherCost.monthId].
  static final monthId =
      obx.QueryStringProperty<OtherCost>(_entities[3].properties[6]);
}

/// [Payment] entity fields to define ObjectBox queries.
class Payment_ {
  /// See [Payment.id].
  static final id =
      obx.QueryIntegerProperty<Payment>(_entities[4].properties[0]);

  /// See [Payment.memberId].
  static final memberId =
      obx.QueryIntegerProperty<Payment>(_entities[4].properties[1]);

  /// See [Payment.amount].
  static final amount =
      obx.QueryDoubleProperty<Payment>(_entities[4].properties[2]);

  /// See [Payment.method].
  static final method =
      obx.QueryStringProperty<Payment>(_entities[4].properties[3]);

  /// See [Payment.note].
  static final note =
      obx.QueryStringProperty<Payment>(_entities[4].properties[4]);

  /// See [Payment.date].
  static final date =
      obx.QueryDateProperty<Payment>(_entities[4].properties[5]);

  /// See [Payment.monthId].
  static final monthId =
      obx.QueryStringProperty<Payment>(_entities[4].properties[6]);
}
